# coding: utf-8

"""
    Proxy Smart

    SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia

    The version of the OpenAPI document: 0.0.1-alpha.202510130118.b027dfe
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List
from api_client.models.post_proxy_smart_backend_by_server_name_by_fhir_version_cache_refresh200_response_server_info import PostProxySmartBackendByServerNameByFhirVersionCacheRefresh200ResponseServerInfo
from typing import Optional, Set
from typing_extensions import Self

class PostProxySmartBackendByServerNameByFhirVersionCacheRefresh200Response(BaseModel):
    """
    PostProxySmartBackendByServerNameByFhirVersionCacheRefresh200Response
    """ # noqa: E501
    success: StrictBool = Field(description="Whether refresh was successful")
    message: StrictStr = Field(description="Success message")
    server_info: PostProxySmartBackendByServerNameByFhirVersionCacheRefresh200ResponseServerInfo = Field(alias="serverInfo")
    __properties: ClassVar[List[str]] = ["success", "message", "serverInfo"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PostProxySmartBackendByServerNameByFhirVersionCacheRefresh200Response from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of server_info
        if self.server_info:
            _dict['serverInfo'] = self.server_info.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PostProxySmartBackendByServerNameByFhirVersionCacheRefresh200Response from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "success": obj.get("success"),
            "message": obj.get("message"),
            "serverInfo": PostProxySmartBackendByServerNameByFhirVersionCacheRefresh200ResponseServerInfo.from_dict(obj["serverInfo"]) if obj.get("serverInfo") is not None else None
        })
        return _obj


