# coding: utf-8

"""
    Proxy Smart

    SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia

    The version of the OpenAPI document: 0.0.1-alpha.202510130118.b027dfe
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class SmartApp(BaseModel):
    """
    SmartApp
    """ # noqa: E501
    id: Optional[StrictStr] = Field(default=None, description="Internal ID")
    client_id: Optional[StrictStr] = Field(default=None, description="OAuth2 client ID", alias="clientId")
    name: Optional[StrictStr] = Field(default=None, description="Application name")
    description: Optional[StrictStr] = Field(default=None, description="Application description")
    enabled: Optional[StrictBool] = Field(default=None, description="Whether the app is enabled")
    protocol: Optional[StrictStr] = Field(default=None, description="Protocol (openid-connect)")
    public_client: Optional[StrictBool] = Field(default=None, description="Whether this is a public client", alias="publicClient")
    redirect_uris: Optional[List[StrictStr]] = Field(default=None, description="Allowed redirect URIs", alias="redirectUris")
    web_origins: Optional[List[StrictStr]] = Field(default=None, description="Allowed web origins (CORS)", alias="webOrigins")
    attributes: Optional[Dict[str, Any]] = None
    client_authenticator_type: Optional[StrictStr] = Field(default=None, description="Client authentication method", alias="clientAuthenticatorType")
    service_accounts_enabled: Optional[StrictBool] = Field(default=None, description="Enable service accounts", alias="serviceAccountsEnabled")
    standard_flow_enabled: Optional[StrictBool] = Field(default=None, description="Enable authorization code flow", alias="standardFlowEnabled")
    implicit_flow_enabled: Optional[StrictBool] = Field(default=None, description="Enable implicit flow", alias="implicitFlowEnabled")
    direct_access_grants_enabled: Optional[StrictBool] = Field(default=None, description="Enable direct access grants", alias="directAccessGrantsEnabled")
    default_client_scopes: Optional[List[StrictStr]] = Field(default=None, description="Default scopes", alias="defaultClientScopes")
    optional_client_scopes: Optional[List[StrictStr]] = Field(default=None, description="Optional scopes", alias="optionalClientScopes")
    app_type: Optional[StrictStr] = Field(default=None, alias="appType")
    access: Optional[Dict[str, Any]] = None
    __properties: ClassVar[List[str]] = ["id", "clientId", "name", "description", "enabled", "protocol", "publicClient", "redirectUris", "webOrigins", "attributes", "clientAuthenticatorType", "serviceAccountsEnabled", "standardFlowEnabled", "implicitFlowEnabled", "directAccessGrantsEnabled", "defaultClientScopes", "optionalClientScopes", "appType", "access"]

    @field_validator('app_type')
    def app_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['standalone-app', 'ehr-launch', 'backend-service', 'agent']):
            raise ValueError("must be one of enum values ('standalone-app', 'ehr-launch', 'backend-service', 'agent')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SmartApp from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SmartApp from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "clientId": obj.get("clientId"),
            "name": obj.get("name"),
            "description": obj.get("description"),
            "enabled": obj.get("enabled"),
            "protocol": obj.get("protocol"),
            "publicClient": obj.get("publicClient"),
            "redirectUris": obj.get("redirectUris"),
            "webOrigins": obj.get("webOrigins"),
            "attributes": obj.get("attributes"),
            "clientAuthenticatorType": obj.get("clientAuthenticatorType"),
            "serviceAccountsEnabled": obj.get("serviceAccountsEnabled"),
            "standardFlowEnabled": obj.get("standardFlowEnabled"),
            "implicitFlowEnabled": obj.get("implicitFlowEnabled"),
            "directAccessGrantsEnabled": obj.get("directAccessGrantsEnabled"),
            "defaultClientScopes": obj.get("defaultClientScopes"),
            "optionalClientScopes": obj.get("optionalClientScopes"),
            "appType": obj.get("appType"),
            "access": obj.get("access")
        })
        return _obj


