# coding: utf-8

"""
    Proxy Smart

    SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia

    The version of the OpenAPI document: 0.0.1-beta.202508171209.d59444a
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from api_client.models.post_auth_token200_response_authorization_details_inner import PostAuthToken200ResponseAuthorizationDetailsInner

class TestPostAuthToken200ResponseAuthorizationDetailsInner(unittest.TestCase):
    """PostAuthToken200ResponseAuthorizationDetailsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostAuthToken200ResponseAuthorizationDetailsInner:
        """Test PostAuthToken200ResponseAuthorizationDetailsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostAuthToken200ResponseAuthorizationDetailsInner`
        """
        model = PostAuthToken200ResponseAuthorizationDetailsInner()
        if include_optional:
            return PostAuthToken200ResponseAuthorizationDetailsInner(
                type = '',
                locations = [
                    ''
                    ],
                fhir_versions = [
                    ''
                    ],
                scope = '',
                patient = '',
                encounter = '',
                fhir_context = [
                    api_client.models.post_auth_token_200_response_fhir_context_inner.postAuthToken_200_response_fhirContext_inner(
                        reference = '', 
                        canonical = '', 
                        identifier = api_client.models.identifier.identifier(), 
                        type = '', 
                        role = '', )
                    ]
            )
        else:
            return PostAuthToken200ResponseAuthorizationDetailsInner(
                type = '',
                locations = [
                    ''
                    ],
                fhir_versions = [
                    ''
                    ],
        )
        """

    def testPostAuthToken200ResponseAuthorizationDetailsInner(self):
        """Test PostAuthToken200ResponseAuthorizationDetailsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
