# coding: utf-8

"""
    Proxy Smart

    SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia

    The version of the OpenAPI document: 0.0.1-beta.202508171209.d59444a
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from api_client.models.post_admin_launch_contexts_by_user_id_fhir_context_request import PostAdminLaunchContextsByUserIdFhirContextRequest

class TestPostAdminLaunchContextsByUserIdFhirContextRequest(unittest.TestCase):
    """PostAdminLaunchContextsByUserIdFhirContextRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostAdminLaunchContextsByUserIdFhirContextRequest:
        """Test PostAdminLaunchContextsByUserIdFhirContextRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostAdminLaunchContextsByUserIdFhirContextRequest`
        """
        model = PostAdminLaunchContextsByUserIdFhirContextRequest()
        if include_optional:
            return PostAdminLaunchContextsByUserIdFhirContextRequest(
                fhir_context = ''
            )
        else:
            return PostAdminLaunchContextsByUserIdFhirContextRequest(
                fhir_context = '',
        )
        """

    def testPostAdminLaunchContextsByUserIdFhirContextRequest(self):
        """Test PostAdminLaunchContextsByUserIdFhirContextRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
