# coding: utf-8

"""
    Proxy Smart

    SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia

    The version of the OpenAPI document: 0.0.1-beta.202508171209.d59444a
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from api_client.models.put_admin_smart_apps_by_client_id_request import PutAdminSmartAppsByClientIdRequest

class TestPutAdminSmartAppsByClientIdRequest(unittest.TestCase):
    """PutAdminSmartAppsByClientIdRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PutAdminSmartAppsByClientIdRequest:
        """Test PutAdminSmartAppsByClientIdRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PutAdminSmartAppsByClientIdRequest`
        """
        model = PutAdminSmartAppsByClientIdRequest()
        if include_optional:
            return PutAdminSmartAppsByClientIdRequest(
                name = '',
                description = '',
                enabled = True,
                redirect_uris = [
                    ''
                    ],
                web_origins = [
                    ''
                    ],
                default_scopes = [
                    ''
                    ],
                optional_scopes = [
                    ''
                    ],
                smart_version = '',
                fhir_version = ''
            )
        else:
            return PutAdminSmartAppsByClientIdRequest(
        )
        """

    def testPutAdminSmartAppsByClientIdRequest(self):
        """Test PutAdminSmartAppsByClientIdRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
