# coding: utf-8

"""
    Proxy Smart

    SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia

    The version of the OpenAPI document: 0.0.1-beta.202508171209.d59444a
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from api_client.models.get_admin_roles200_response_inner import GetAdminRoles200ResponseInner

class TestGetAdminRoles200ResponseInner(unittest.TestCase):
    """GetAdminRoles200ResponseInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetAdminRoles200ResponseInner:
        """Test GetAdminRoles200ResponseInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetAdminRoles200ResponseInner`
        """
        model = GetAdminRoles200ResponseInner()
        if include_optional:
            return GetAdminRoles200ResponseInner(
                id = '',
                name = '',
                description = '',
                attributes = None
            )
        else:
            return GetAdminRoles200ResponseInner(
        )
        """

    def testGetAdminRoles200ResponseInner(self):
        """Test GetAdminRoles200ResponseInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
