# coding: utf-8

"""
    Proxy Smart

    SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia

    The version of the OpenAPI document: 0.0.1-beta.202508171209.d59444a
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from api_client.models.get_admin_keycloak_config_status200_response import GetAdminKeycloakConfigStatus200Response

class TestGetAdminKeycloakConfigStatus200Response(unittest.TestCase):
    """GetAdminKeycloakConfigStatus200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetAdminKeycloakConfigStatus200Response:
        """Test GetAdminKeycloakConfigStatus200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetAdminKeycloakConfigStatus200Response`
        """
        model = GetAdminKeycloakConfigStatus200Response()
        if include_optional:
            return GetAdminKeycloakConfigStatus200Response(
                base_url = '',
                realm = '',
                has_admin_client = True,
                admin_client_id = ''
            )
        else:
            return GetAdminKeycloakConfigStatus200Response(
                base_url = '',
                realm = '',
                has_admin_client = True,
                admin_client_id = '',
        )
        """

    def testGetAdminKeycloakConfigStatus200Response(self):
        """Test GetAdminKeycloakConfigStatus200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
