# coding: utf-8

"""
    Proxy Smart

    SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia

    The version of the OpenAPI document: 0.0.1-alpha.202510130118.b027dfe
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from api_client.models.get_monitoring_oauth_health200_response_alerts_inner import GetMonitoringOauthHealth200ResponseAlertsInner

class TestGetMonitoringOauthHealth200ResponseAlertsInner(unittest.TestCase):
    """GetMonitoringOauthHealth200ResponseAlertsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetMonitoringOauthHealth200ResponseAlertsInner:
        """Test GetMonitoringOauthHealth200ResponseAlertsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetMonitoringOauthHealth200ResponseAlertsInner`
        """
        model = GetMonitoringOauthHealth200ResponseAlertsInner()
        if include_optional:
            return GetMonitoringOauthHealth200ResponseAlertsInner(
                type = '',
                message = ''
            )
        else:
            return GetMonitoringOauthHealth200ResponseAlertsInner(
                type = '',
                message = '',
        )
        """

    def testGetMonitoringOauthHealth200ResponseAlertsInner(self):
        """Test GetMonitoringOauthHealth200ResponseAlertsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
