# coding: utf-8

"""
    Proxy Smart

    SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia

    The version of the OpenAPI document: 0.0.1-beta.202508171209.d59444a
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from api_client.models.get_health200_response import GetHealth200Response

class TestGetHealth200Response(unittest.TestCase):
    """GetHealth200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetHealth200Response:
        """Test GetHealth200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetHealth200Response`
        """
        model = GetHealth200Response()
        if include_optional:
            return GetHealth200Response(
                status = '',
                timestamp = '',
                uptime = 1.337
            )
        else:
            return GetHealth200Response(
                status = '',
                timestamp = '',
                uptime = 1.337,
        )
        """

    def testGetHealth200Response(self):
        """Test GetHealth200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
