# coding: utf-8

"""
    Proxy Smart

    SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia

    The version of the OpenAPI document: 0.0.1-beta.202508171209.d59444a
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from api_client.models.put_fhir_servers_by_server_id_mtls200_response_config import PutFhirServersByServerIdMtls200ResponseConfig

class TestPutFhirServersByServerIdMtls200ResponseConfig(unittest.TestCase):
    """PutFhirServersByServerIdMtls200ResponseConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PutFhirServersByServerIdMtls200ResponseConfig:
        """Test PutFhirServersByServerIdMtls200ResponseConfig
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PutFhirServersByServerIdMtls200ResponseConfig`
        """
        model = PutFhirServersByServerIdMtls200ResponseConfig()
        if include_optional:
            return PutFhirServersByServerIdMtls200ResponseConfig(
                enabled = True,
                has_certificates = api_client.models.get_fhir_servers_by_server_id_mtls_200_response_has_certificates.getFhir_serversByServer_idMtls_200_response_hasCertificates(
                    client_cert = True, 
                    client_key = True, 
                    ca_cert = True, )
            )
        else:
            return PutFhirServersByServerIdMtls200ResponseConfig(
                enabled = True,
                has_certificates = api_client.models.get_fhir_servers_by_server_id_mtls_200_response_has_certificates.getFhir_serversByServer_idMtls_200_response_hasCertificates(
                    client_cert = True, 
                    client_key = True, 
                    ca_cert = True, ),
        )
        """

    def testPutFhirServersByServerIdMtls200ResponseConfig(self):
        """Test PutFhirServersByServerIdMtls200ResponseConfig"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
