# coding: utf-8

"""
    Proxy Smart

    SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia

    The version of the OpenAPI document: 0.0.1-beta.202508171209.d59444a
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from api_client.models.post_admin_keycloak_config_configure_request import PostAdminKeycloakConfigConfigureRequest

class TestPostAdminKeycloakConfigConfigureRequest(unittest.TestCase):
    """PostAdminKeycloakConfigConfigureRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostAdminKeycloakConfigConfigureRequest:
        """Test PostAdminKeycloakConfigConfigureRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostAdminKeycloakConfigConfigureRequest`
        """
        model = PostAdminKeycloakConfigConfigureRequest()
        if include_optional:
            return PostAdminKeycloakConfigConfigureRequest(
                base_url = '',
                realm = '',
                admin_client_id = '',
                admin_client_secret = ''
            )
        else:
            return PostAdminKeycloakConfigConfigureRequest(
                base_url = '',
                realm = '',
        )
        """

    def testPostAdminKeycloakConfigConfigureRequest(self):
        """Test PostAdminKeycloakConfigConfigureRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
