# coding: utf-8

"""
    Proxy Smart

    SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia

    The version of the OpenAPI document: 0.0.1-beta.202508171209.d59444a
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from api_client.models.post_admin_keycloak_config_test_request import PostAdminKeycloakConfigTestRequest

class TestPostAdminKeycloakConfigTestRequest(unittest.TestCase):
    """PostAdminKeycloakConfigTestRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostAdminKeycloakConfigTestRequest:
        """Test PostAdminKeycloakConfigTestRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostAdminKeycloakConfigTestRequest`
        """
        model = PostAdminKeycloakConfigTestRequest()
        if include_optional:
            return PostAdminKeycloakConfigTestRequest(
                base_url = '',
                realm = ''
            )
        else:
            return PostAdminKeycloakConfigTestRequest(
                base_url = '',
                realm = '',
        )
        """

    def testPostAdminKeycloakConfigTestRequest(self):
        """Test PostAdminKeycloakConfigTestRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
