# coding: utf-8

"""
    Proxy Smart

    SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia

    The version of the OpenAPI document: 0.0.1-beta.202508171209.d59444a
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from api_client.models.post_admin_keycloak_config_test200_response import PostAdminKeycloakConfigTest200Response

class TestPostAdminKeycloakConfigTest200Response(unittest.TestCase):
    """PostAdminKeycloakConfigTest200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostAdminKeycloakConfigTest200Response:
        """Test PostAdminKeycloakConfigTest200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostAdminKeycloakConfigTest200Response`
        """
        model = PostAdminKeycloakConfigTest200Response()
        if include_optional:
            return PostAdminKeycloakConfigTest200Response(
                success = True,
                message = '',
                error = ''
            )
        else:
            return PostAdminKeycloakConfigTest200Response(
                success = True,
        )
        """

    def testPostAdminKeycloakConfigTest200Response(self):
        """Test PostAdminKeycloakConfigTest200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
