# coding: utf-8

"""
    Proxy Smart

    SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia

    The version of the OpenAPI document: 0.0.1-beta.202508171209.d59444a
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from api_client.models.get_status200_response_keycloak import GetStatus200ResponseKeycloak

class TestGetStatus200ResponseKeycloak(unittest.TestCase):
    """GetStatus200ResponseKeycloak unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetStatus200ResponseKeycloak:
        """Test GetStatus200ResponseKeycloak
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetStatus200ResponseKeycloak`
        """
        model = GetStatus200ResponseKeycloak()
        if include_optional:
            return GetStatus200ResponseKeycloak(
                status = '',
                accessible = True,
                realm = '',
                last_connected = ''
            )
        else:
            return GetStatus200ResponseKeycloak(
                status = '',
                accessible = True,
                realm = '',
        )
        """

    def testGetStatus200ResponseKeycloak(self):
        """Test GetStatus200ResponseKeycloak"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
