# coding: utf-8

"""
    Proxy Smart

    SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia

    The version of the OpenAPI document: 0.0.1-beta.202508171209.d59444a
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from api_client.models.put_admin_launch_contexts_by_user_id_intent_request import PutAdminLaunchContextsByUserIdIntentRequest

class TestPutAdminLaunchContextsByUserIdIntentRequest(unittest.TestCase):
    """PutAdminLaunchContextsByUserIdIntentRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PutAdminLaunchContextsByUserIdIntentRequest:
        """Test PutAdminLaunchContextsByUserIdIntentRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PutAdminLaunchContextsByUserIdIntentRequest`
        """
        model = PutAdminLaunchContextsByUserIdIntentRequest()
        if include_optional:
            return PutAdminLaunchContextsByUserIdIntentRequest(
                intent = ''
            )
        else:
            return PutAdminLaunchContextsByUserIdIntentRequest(
                intent = '',
        )
        """

    def testPutAdminLaunchContextsByUserIdIntentRequest(self):
        """Test PutAdminLaunchContextsByUserIdIntentRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
