# coding: utf-8

"""
    Proxy Smart

    SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia

    The version of the OpenAPI document: 0.0.1-alpha.202510130118.b027dfe
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from api_client.models.get_oauth_monitoring_websocket_info200_response import GetOauthMonitoringWebsocketInfo200Response

class TestGetOauthMonitoringWebsocketInfo200Response(unittest.TestCase):
    """GetOauthMonitoringWebsocketInfo200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetOauthMonitoringWebsocketInfo200Response:
        """Test GetOauthMonitoringWebsocketInfo200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetOauthMonitoringWebsocketInfo200Response`
        """
        model = GetOauthMonitoringWebsocketInfo200Response()
        if include_optional:
            return GetOauthMonitoringWebsocketInfo200Response(
                endpoint = '',
                protocol = '',
                supported_messages = [
                    ''
                    ],
                subscription_types = [
                    ''
                    ]
            )
        else:
            return GetOauthMonitoringWebsocketInfo200Response(
                endpoint = '',
                protocol = '',
                supported_messages = [
                    ''
                    ],
                subscription_types = [
                    ''
                    ],
        )
        """

    def testGetOauthMonitoringWebsocketInfo200Response(self):
        """Test GetOauthMonitoringWebsocketInfo200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
