services:
  keycloak:
    environment:
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080
      KC_PROXY: edge
      KC_CACHE: ispn
      KC_CACHE_STACK: tcp
    command:
      - start
      - --import-realm

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: proxy-smart-backend
    environment:
      NODE_ENV: production
      PORT: 8445
      BASE_URL: http://localhost:8445
      KEYCLOAK_BASE_URL: http://keycloak:8080
      KEYCLOAK_DOMAIN: localhost
      KEYCLOAK_REALM: proxy-smart
      KEYCLOAK_JWKS_URI: http://keycloak:8080/realms/proxy-smart/protocol/openid-connect/certs
      KEYCLOAK_ADMIN_CLIENT_ID: admin-service
      KEYCLOAK_ADMIN_CLIENT_SECRET: admin-service-secret
      FHIR_SERVER_BASE: https://hapi.fhir.org/baseR4,https://server.fire.ly # Multiple FHIR servers can be specified, separated by commas
    ports:
      - "8445:8445"
    depends_on:
      keycloak:
        condition: service_healthy
    networks:
      - proxy-smart

  frontend:
    build:
      context: ./ui
      dockerfile: Dockerfile
    container_name: proxy-smart-frontend
    environment:
      VITE_API_BASE_URL: http://localhost:8445
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - proxy-smart

networks:
  proxy-smart:
    name: proxy-smart-network
    driver: bridge
