/* tslint:disable */
/* eslint-disable */
/**
 * Proxy Smart
 * SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia
 *
 * The version of the OpenAPI document: 0.0.1-alpha.202510130118.b027dfe
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AlertInfo
 */
export interface AlertInfo {
    /**
     * Alert type (info, warning, error)
     * @type {string}
     * @memberof AlertInfo
     */
    type: string;
    /**
     * Alert message
     * @type {string}
     * @memberof AlertInfo
     */
    message: string;
}

/**
 * Check if a given object implements the AlertInfo interface.
 */
export function instanceOfAlertInfo(value: object): value is AlertInfo {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function AlertInfoFromJSON(json: any): AlertInfo {
    return AlertInfoFromJSONTyped(json, false);
}

export function AlertInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AlertInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'message': json['message'],
    };
}

export function AlertInfoToJSON(json: any): AlertInfo {
    return AlertInfoToJSONTyped(json, false);
}

export function AlertInfoToJSONTyped(value?: AlertInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'message': value['message'],
    };
}

