/* tslint:disable */
/* eslint-disable */
/**
 * Proxy Smart
 * SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia
 *
 * The version of the OpenAPI document: 0.0.1-RELEASE.202510170109.139bb12
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ClientRegistrationRequest
 */
export interface ClientRegistrationRequest {
    /**
     * Array of redirect URIs for the client
     * @type {Array<string>}
     * @memberof ClientRegistrationRequest
     */
    redirectUris: Array<string>;
    /**
     * Human-readable client name
     * @type {string}
     * @memberof ClientRegistrationRequest
     */
    clientName?: string;
    /**
     * Client home page URL
     * @type {string}
     * @memberof ClientRegistrationRequest
     */
    clientUri?: string;
    /**
     * Client logo URL
     * @type {string}
     * @memberof ClientRegistrationRequest
     */
    logoUri?: string;
    /**
     * Requested scopes (space-separated)
     * @type {string}
     * @memberof ClientRegistrationRequest
     */
    scope?: string;
    /**
     * Contact email addresses
     * @type {Array<string>}
     * @memberof ClientRegistrationRequest
     */
    contacts?: Array<string>;
    /**
     * Terms of service URL
     * @type {string}
     * @memberof ClientRegistrationRequest
     */
    tosUri?: string;
    /**
     * Privacy policy URL
     * @type {string}
     * @memberof ClientRegistrationRequest
     */
    policyUri?: string;
    /**
     * JWKS endpoint URL
     * @type {string}
     * @memberof ClientRegistrationRequest
     */
    jwksUri?: string;
    /**
     * JSON Web Key Set
     * @type {object}
     * @memberof ClientRegistrationRequest
     */
    jwks?: object;
    /**
     * Software identifier
     * @type {string}
     * @memberof ClientRegistrationRequest
     */
    softwareId?: string;
    /**
     * Software version
     * @type {string}
     * @memberof ClientRegistrationRequest
     */
    softwareVersion?: string;
    /**
     * Supported FHIR versions
     * @type {Array<string>}
     * @memberof ClientRegistrationRequest
     */
    fhirVersions?: Array<string>;
    /**
     * EHR launch URLs
     * @type {Array<string>}
     * @memberof ClientRegistrationRequest
     */
    launchUris?: Array<string>;
}

/**
 * Check if a given object implements the ClientRegistrationRequest interface.
 */
export function instanceOfClientRegistrationRequest(value: object): value is ClientRegistrationRequest {
    if (!('redirectUris' in value) || value['redirectUris'] === undefined) return false;
    return true;
}

export function ClientRegistrationRequestFromJSON(json: any): ClientRegistrationRequest {
    return ClientRegistrationRequestFromJSONTyped(json, false);
}

export function ClientRegistrationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClientRegistrationRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'redirectUris': json['redirect_uris'],
        'clientName': json['client_name'] == null ? undefined : json['client_name'],
        'clientUri': json['client_uri'] == null ? undefined : json['client_uri'],
        'logoUri': json['logo_uri'] == null ? undefined : json['logo_uri'],
        'scope': json['scope'] == null ? undefined : json['scope'],
        'contacts': json['contacts'] == null ? undefined : json['contacts'],
        'tosUri': json['tos_uri'] == null ? undefined : json['tos_uri'],
        'policyUri': json['policy_uri'] == null ? undefined : json['policy_uri'],
        'jwksUri': json['jwks_uri'] == null ? undefined : json['jwks_uri'],
        'jwks': json['jwks'] == null ? undefined : json['jwks'],
        'softwareId': json['software_id'] == null ? undefined : json['software_id'],
        'softwareVersion': json['software_version'] == null ? undefined : json['software_version'],
        'fhirVersions': json['fhir_versions'] == null ? undefined : json['fhir_versions'],
        'launchUris': json['launch_uris'] == null ? undefined : json['launch_uris'],
    };
}

export function ClientRegistrationRequestToJSON(json: any): ClientRegistrationRequest {
    return ClientRegistrationRequestToJSONTyped(json, false);
}

export function ClientRegistrationRequestToJSONTyped(value?: ClientRegistrationRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'redirect_uris': value['redirectUris'],
        'client_name': value['clientName'],
        'client_uri': value['clientUri'],
        'logo_uri': value['logoUri'],
        'scope': value['scope'],
        'contacts': value['contacts'],
        'tos_uri': value['tosUri'],
        'policy_uri': value['policyUri'],
        'jwks_uri': value['jwksUri'],
        'jwks': value['jwks'],
        'software_id': value['softwareId'],
        'software_version': value['softwareVersion'],
        'fhir_versions': value['fhirVersions'],
        'launch_uris': value['launchUris'],
    };
}

