/* tslint:disable */
/* eslint-disable */
/**
 * Proxy Smart
 * SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia
 *
 * The version of the OpenAPI document: 0.0.1-alpha.202510130118.b027dfe
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FhirServerListServersInnerEndpoints } from './FhirServerListServersInnerEndpoints';
import {
    FhirServerListServersInnerEndpointsFromJSON,
    FhirServerListServersInnerEndpointsFromJSONTyped,
    FhirServerListServersInnerEndpointsToJSON,
    FhirServerListServersInnerEndpointsToJSONTyped,
} from './FhirServerListServersInnerEndpoints';

/**
 * 
 * @export
 * @interface FhirServerListServersInner
 */
export interface FhirServerListServersInner {
    /**
     * Server ID
     * @type {string}
     * @memberof FhirServerListServersInner
     */
    id: string;
    /**
     * Server identifier/name
     * @type {string}
     * @memberof FhirServerListServersInner
     */
    name: string;
    /**
     * Base URL of the FHIR server
     * @type {string}
     * @memberof FhirServerListServersInner
     */
    url: string;
    /**
     * FHIR version (e.g., R4, R5)
     * @type {string}
     * @memberof FhirServerListServersInner
     */
    fhirVersion: string;
    /**
     * FHIR server software version
     * @type {string}
     * @memberof FhirServerListServersInner
     */
    serverVersion?: string;
    /**
     * FHIR server software name
     * @type {string}
     * @memberof FhirServerListServersInner
     */
    serverName?: string;
    /**
     * Whether the server is supported by this proxy
     * @type {boolean}
     * @memberof FhirServerListServersInner
     */
    supported: boolean;
    /**
     * Error message if server is not reachable
     * @type {string}
     * @memberof FhirServerListServersInner
     */
    error?: string;
    /**
     * 
     * @type {FhirServerListServersInnerEndpoints}
     * @memberof FhirServerListServersInner
     */
    endpoints: FhirServerListServersInnerEndpoints;
}

/**
 * Check if a given object implements the FhirServerListServersInner interface.
 */
export function instanceOfFhirServerListServersInner(value: object): value is FhirServerListServersInner {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    if (!('fhirVersion' in value) || value['fhirVersion'] === undefined) return false;
    if (!('supported' in value) || value['supported'] === undefined) return false;
    if (!('endpoints' in value) || value['endpoints'] === undefined) return false;
    return true;
}

export function FhirServerListServersInnerFromJSON(json: any): FhirServerListServersInner {
    return FhirServerListServersInnerFromJSONTyped(json, false);
}

export function FhirServerListServersInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): FhirServerListServersInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'url': json['url'],
        'fhirVersion': json['fhirVersion'],
        'serverVersion': json['serverVersion'] == null ? undefined : json['serverVersion'],
        'serverName': json['serverName'] == null ? undefined : json['serverName'],
        'supported': json['supported'],
        'error': json['error'] == null ? undefined : json['error'],
        'endpoints': FhirServerListServersInnerEndpointsFromJSON(json['endpoints']),
    };
}

export function FhirServerListServersInnerToJSON(json: any): FhirServerListServersInner {
    return FhirServerListServersInnerToJSONTyped(json, false);
}

export function FhirServerListServersInnerToJSONTyped(value?: FhirServerListServersInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'url': value['url'],
        'fhirVersion': value['fhirVersion'],
        'serverVersion': value['serverVersion'],
        'serverName': value['serverName'],
        'supported': value['supported'],
        'error': value['error'],
        'endpoints': FhirServerListServersInnerEndpointsToJSON(value['endpoints']),
    };
}

