/* tslint:disable */
/* eslint-disable */
/**
 * Proxy Smart
 * SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia
 *
 * The version of the OpenAPI document: 0.0.1-RELEASE.202510170109.139bb12
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IdentityProviderResponse
 */
export interface IdentityProviderResponse {
    /**
     * Provider alias
     * @type {string}
     * @memberof IdentityProviderResponse
     */
    alias?: string;
    /**
     * Provider type
     * @type {string}
     * @memberof IdentityProviderResponse
     */
    providerId?: string;
    /**
     * Display name
     * @type {string}
     * @memberof IdentityProviderResponse
     */
    displayName?: string;
    /**
     * Whether provider is enabled
     * @type {boolean}
     * @memberof IdentityProviderResponse
     */
    enabled?: boolean;
    /**
     * 
     * @type {object}
     * @memberof IdentityProviderResponse
     */
    config?: object;
    /**
     * 
     * @type {boolean}
     * @memberof IdentityProviderResponse
     */
    addReadTokenRoleOnCreate?: boolean;
    /**
     * 
     * @type {string}
     * @memberof IdentityProviderResponse
     */
    firstBrokerLoginFlowAlias?: string;
    /**
     * 
     * @type {string}
     * @memberof IdentityProviderResponse
     */
    internalId?: string;
    /**
     * 
     * @type {boolean}
     * @memberof IdentityProviderResponse
     */
    linkOnly?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof IdentityProviderResponse
     */
    hideOnLogin?: boolean;
    /**
     * 
     * @type {string}
     * @memberof IdentityProviderResponse
     */
    postBrokerLoginFlowAlias?: string;
    /**
     * 
     * @type {boolean}
     * @memberof IdentityProviderResponse
     */
    storeToken?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof IdentityProviderResponse
     */
    trustEmail?: boolean;
    /**
     * 
     * @type {string}
     * @memberof IdentityProviderResponse
     */
    organizationId?: string;
}

/**
 * Check if a given object implements the IdentityProviderResponse interface.
 */
export function instanceOfIdentityProviderResponse(value: object): value is IdentityProviderResponse {
    return true;
}

export function IdentityProviderResponseFromJSON(json: any): IdentityProviderResponse {
    return IdentityProviderResponseFromJSONTyped(json, false);
}

export function IdentityProviderResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): IdentityProviderResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'alias': json['alias'] == null ? undefined : json['alias'],
        'providerId': json['providerId'] == null ? undefined : json['providerId'],
        'displayName': json['displayName'] == null ? undefined : json['displayName'],
        'enabled': json['enabled'] == null ? undefined : json['enabled'],
        'config': json['config'] == null ? undefined : json['config'],
        'addReadTokenRoleOnCreate': json['addReadTokenRoleOnCreate'] == null ? undefined : json['addReadTokenRoleOnCreate'],
        'firstBrokerLoginFlowAlias': json['firstBrokerLoginFlowAlias'] == null ? undefined : json['firstBrokerLoginFlowAlias'],
        'internalId': json['internalId'] == null ? undefined : json['internalId'],
        'linkOnly': json['linkOnly'] == null ? undefined : json['linkOnly'],
        'hideOnLogin': json['hideOnLogin'] == null ? undefined : json['hideOnLogin'],
        'postBrokerLoginFlowAlias': json['postBrokerLoginFlowAlias'] == null ? undefined : json['postBrokerLoginFlowAlias'],
        'storeToken': json['storeToken'] == null ? undefined : json['storeToken'],
        'trustEmail': json['trustEmail'] == null ? undefined : json['trustEmail'],
        'organizationId': json['organizationId'] == null ? undefined : json['organizationId'],
    };
}

export function IdentityProviderResponseToJSON(json: any): IdentityProviderResponse {
    return IdentityProviderResponseToJSONTyped(json, false);
}

export function IdentityProviderResponseToJSONTyped(value?: IdentityProviderResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'alias': value['alias'],
        'providerId': value['providerId'],
        'displayName': value['displayName'],
        'enabled': value['enabled'],
        'config': value['config'],
        'addReadTokenRoleOnCreate': value['addReadTokenRoleOnCreate'],
        'firstBrokerLoginFlowAlias': value['firstBrokerLoginFlowAlias'],
        'internalId': value['internalId'],
        'linkOnly': value['linkOnly'],
        'hideOnLogin': value['hideOnLogin'],
        'postBrokerLoginFlowAlias': value['postBrokerLoginFlowAlias'],
        'storeToken': value['storeToken'],
        'trustEmail': value['trustEmail'],
        'organizationId': value['organizationId'],
    };
}

