/* tslint:disable */
/* eslint-disable */
/**
 * Proxy Smart
 * SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia
 *
 * The version of the OpenAPI document: 0.0.1-RELEASE.202510170109.139bb12
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * HTTP request context
 * @export
 * @interface OAuthEventRequestDetails
 */
export interface OAuthEventRequestDetails {
    /**
     * Requested path
     * @type {string}
     * @memberof OAuthEventRequestDetails
     */
    path: string;
    /**
     * HTTP method
     * @type {string}
     * @memberof OAuthEventRequestDetails
     */
    method: string;
    /**
     * Request headers
     * @type {object}
     * @memberof OAuthEventRequestDetails
     */
    headers?: object;
}

/**
 * Check if a given object implements the OAuthEventRequestDetails interface.
 */
export function instanceOfOAuthEventRequestDetails(value: object): value is OAuthEventRequestDetails {
    if (!('path' in value) || value['path'] === undefined) return false;
    if (!('method' in value) || value['method'] === undefined) return false;
    return true;
}

export function OAuthEventRequestDetailsFromJSON(json: any): OAuthEventRequestDetails {
    return OAuthEventRequestDetailsFromJSONTyped(json, false);
}

export function OAuthEventRequestDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): OAuthEventRequestDetails {
    if (json == null) {
        return json;
    }
    return {
        
        'path': json['path'],
        'method': json['method'],
        'headers': json['headers'] == null ? undefined : json['headers'],
    };
}

export function OAuthEventRequestDetailsToJSON(json: any): OAuthEventRequestDetails {
    return OAuthEventRequestDetailsToJSONTyped(json, false);
}

export function OAuthEventRequestDetailsToJSONTyped(value?: OAuthEventRequestDetails | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'path': value['path'],
        'method': value['method'],
        'headers': value['headers'],
    };
}

