/* tslint:disable */
/* eslint-disable */
/**
 * Proxy Smart
 * SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia
 *
 * The version of the OpenAPI document: 0.0.1-RELEASE.202510170109.139bb12
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OAuthPredictiveInsightsNextHour } from './OAuthPredictiveInsightsNextHour';
import {
    OAuthPredictiveInsightsNextHourFromJSON,
    OAuthPredictiveInsightsNextHourFromJSONTyped,
    OAuthPredictiveInsightsNextHourToJSON,
    OAuthPredictiveInsightsNextHourToJSONTyped,
} from './OAuthPredictiveInsightsNextHour';

/**
 * 
 * @export
 * @interface OAuthPredictiveInsights
 */
export interface OAuthPredictiveInsights {
    /**
     * Timestamp when the prediction was generated
     * @type {string}
     * @memberof OAuthPredictiveInsights
     */
    generatedAt: string;
    /**
     * 
     * @type {string}
     * @memberof OAuthPredictiveInsights
     */
    trendDirection: OAuthPredictiveInsightsTrendDirectionEnum;
    /**
     * Confidence score for the trend (0-1)
     * @type {number}
     * @memberof OAuthPredictiveInsights
     */
    trendConfidence: number;
    /**
     * 
     * @type {OAuthPredictiveInsightsNextHour}
     * @memberof OAuthPredictiveInsights
     */
    nextHour: OAuthPredictiveInsightsNextHour;
    /**
     * 
     * @type {string}
     * @memberof OAuthPredictiveInsights
     */
    anomalyRisk: OAuthPredictiveInsightsAnomalyRiskEnum;
    /**
     * 
     * @type {Array<string>}
     * @memberof OAuthPredictiveInsights
     */
    anomalyReasons: Array<string>;
    /**
     * Human-readable guidance or recommendation
     * @type {string}
     * @memberof OAuthPredictiveInsights
     */
    notes?: string;
}


/**
 * @export
 */
export const OAuthPredictiveInsightsTrendDirectionEnum = {
    Increasing: 'increasing',
    Decreasing: 'decreasing',
    Stable: 'stable'
} as const;
export type OAuthPredictiveInsightsTrendDirectionEnum = typeof OAuthPredictiveInsightsTrendDirectionEnum[keyof typeof OAuthPredictiveInsightsTrendDirectionEnum];

/**
 * @export
 */
export const OAuthPredictiveInsightsAnomalyRiskEnum = {
    Low: 'low',
    Medium: 'medium',
    High: 'high'
} as const;
export type OAuthPredictiveInsightsAnomalyRiskEnum = typeof OAuthPredictiveInsightsAnomalyRiskEnum[keyof typeof OAuthPredictiveInsightsAnomalyRiskEnum];


/**
 * Check if a given object implements the OAuthPredictiveInsights interface.
 */
export function instanceOfOAuthPredictiveInsights(value: object): value is OAuthPredictiveInsights {
    if (!('generatedAt' in value) || value['generatedAt'] === undefined) return false;
    if (!('trendDirection' in value) || value['trendDirection'] === undefined) return false;
    if (!('trendConfidence' in value) || value['trendConfidence'] === undefined) return false;
    if (!('nextHour' in value) || value['nextHour'] === undefined) return false;
    if (!('anomalyRisk' in value) || value['anomalyRisk'] === undefined) return false;
    if (!('anomalyReasons' in value) || value['anomalyReasons'] === undefined) return false;
    return true;
}

export function OAuthPredictiveInsightsFromJSON(json: any): OAuthPredictiveInsights {
    return OAuthPredictiveInsightsFromJSONTyped(json, false);
}

export function OAuthPredictiveInsightsFromJSONTyped(json: any, ignoreDiscriminator: boolean): OAuthPredictiveInsights {
    if (json == null) {
        return json;
    }
    return {
        
        'generatedAt': json['generatedAt'],
        'trendDirection': json['trendDirection'],
        'trendConfidence': json['trendConfidence'],
        'nextHour': OAuthPredictiveInsightsNextHourFromJSON(json['nextHour']),
        'anomalyRisk': json['anomalyRisk'],
        'anomalyReasons': json['anomalyReasons'],
        'notes': json['notes'] == null ? undefined : json['notes'],
    };
}

export function OAuthPredictiveInsightsToJSON(json: any): OAuthPredictiveInsights {
    return OAuthPredictiveInsightsToJSONTyped(json, false);
}

export function OAuthPredictiveInsightsToJSONTyped(value?: OAuthPredictiveInsights | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'generatedAt': value['generatedAt'],
        'trendDirection': value['trendDirection'],
        'trendConfidence': value['trendConfidence'],
        'nextHour': OAuthPredictiveInsightsNextHourToJSON(value['nextHour']),
        'anomalyRisk': value['anomalyRisk'],
        'anomalyReasons': value['anomalyReasons'],
        'notes': value['notes'],
    };
}

