/* tslint:disable */
/* eslint-disable */
/**
 * Proxy Smart
 * SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia
 *
 * The version of the OpenAPI document: 0.0.1-beta.202508171209.d59444a
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostApiAiChat200ResponseMode
 */
export interface PostApiAiChat200ResponseMode {
}

/**
 * Check if a given object implements the PostApiAiChat200ResponseMode interface.
 */
export function instanceOfPostApiAiChat200ResponseMode(value: object): value is PostApiAiChat200ResponseMode {
    return true;
}

export function PostApiAiChat200ResponseModeFromJSON(json: any): PostApiAiChat200ResponseMode {
    return PostApiAiChat200ResponseModeFromJSONTyped(json, false);
}

export function PostApiAiChat200ResponseModeFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostApiAiChat200ResponseMode {
    return json;
}

export function PostApiAiChat200ResponseModeToJSON(json: any): PostApiAiChat200ResponseMode {
    return PostApiAiChat200ResponseModeToJSONTyped(json, false);
}

export function PostApiAiChat200ResponseModeToJSONTyped(value?: PostApiAiChat200ResponseMode | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

