/* tslint:disable */
/* eslint-disable */
/**
 * Proxy Smart
 * SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia
 *
 * The version of the OpenAPI document: 0.0.1-beta.202508171209.d59444a
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostApiAiChatRequest
 */
export interface PostApiAiChatRequest {
    /**
     * User question or prompt for the AI assistant
     * @type {string}
     * @memberof PostApiAiChatRequest
     */
    message: string;
    /**
     * Optional conversation identifier to maintain context between turns
     * @type {string}
     * @memberof PostApiAiChatRequest
     */
    conversationId?: string;
}

/**
 * Check if a given object implements the PostApiAiChatRequest interface.
 */
export function instanceOfPostApiAiChatRequest(value: object): value is PostApiAiChatRequest {
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function PostApiAiChatRequestFromJSON(json: any): PostApiAiChatRequest {
    return PostApiAiChatRequestFromJSONTyped(json, false);
}

export function PostApiAiChatRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostApiAiChatRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
        'conversationId': json['conversationId'] == null ? undefined : json['conversationId'],
    };
}

export function PostApiAiChatRequestToJSON(json: any): PostApiAiChatRequest {
    return PostApiAiChatRequestToJSONTyped(json, false);
}

export function PostApiAiChatRequestToJSONTyped(value?: PostApiAiChatRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'conversationId': value['conversationId'],
    };
}

