/* tslint:disable */
/* eslint-disable */
/**
 * Proxy Smart
 * SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia
 *
 * The version of the OpenAPI document: 0.0.1-RELEASE.202510170109.139bb12
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SaveKeycloakConfigRequest
 */
export interface SaveKeycloakConfigRequest {
    /**
     * Keycloak base URL
     * @type {string}
     * @memberof SaveKeycloakConfigRequest
     */
    baseUrl: string;
    /**
     * Keycloak realm name
     * @type {string}
     * @memberof SaveKeycloakConfigRequest
     */
    realm: string;
    /**
     * Admin client ID for API access
     * @type {string}
     * @memberof SaveKeycloakConfigRequest
     */
    adminClientId?: string;
    /**
     * Admin client secret for API access
     * @type {string}
     * @memberof SaveKeycloakConfigRequest
     */
    adminClientSecret?: string;
}

/**
 * Check if a given object implements the SaveKeycloakConfigRequest interface.
 */
export function instanceOfSaveKeycloakConfigRequest(value: object): value is SaveKeycloakConfigRequest {
    if (!('baseUrl' in value) || value['baseUrl'] === undefined) return false;
    if (!('realm' in value) || value['realm'] === undefined) return false;
    return true;
}

export function SaveKeycloakConfigRequestFromJSON(json: any): SaveKeycloakConfigRequest {
    return SaveKeycloakConfigRequestFromJSONTyped(json, false);
}

export function SaveKeycloakConfigRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SaveKeycloakConfigRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'baseUrl': json['baseUrl'],
        'realm': json['realm'],
        'adminClientId': json['adminClientId'] == null ? undefined : json['adminClientId'],
        'adminClientSecret': json['adminClientSecret'] == null ? undefined : json['adminClientSecret'],
    };
}

export function SaveKeycloakConfigRequestToJSON(json: any): SaveKeycloakConfigRequest {
    return SaveKeycloakConfigRequestToJSONTyped(json, false);
}

export function SaveKeycloakConfigRequestToJSONTyped(value?: SaveKeycloakConfigRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'baseUrl': value['baseUrl'],
        'realm': value['realm'],
        'adminClientId': value['adminClientId'],
        'adminClientSecret': value['adminClientSecret'],
    };
}

