/* tslint:disable */
/* eslint-disable */
/**
 * Proxy Smart
 * SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia
 *
 * The version of the OpenAPI document: 0.0.1-alpha.202510130118.b027dfe
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ServerOperationResponse
 */
export interface ServerOperationResponse {
    /**
     * Whether the operation was successful
     * @type {boolean}
     * @memberof ServerOperationResponse
     */
    success: boolean;
    /**
     * Operation message
     * @type {string}
     * @memberof ServerOperationResponse
     */
    message: string;
    /**
     * Timestamp (ISO 8601)
     * @type {string}
     * @memberof ServerOperationResponse
     */
    timestamp: string;
}

/**
 * Check if a given object implements the ServerOperationResponse interface.
 */
export function instanceOfServerOperationResponse(value: object): value is ServerOperationResponse {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    return true;
}

export function ServerOperationResponseFromJSON(json: any): ServerOperationResponse {
    return ServerOperationResponseFromJSONTyped(json, false);
}

export function ServerOperationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServerOperationResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'message': json['message'],
        'timestamp': json['timestamp'],
    };
}

export function ServerOperationResponseToJSON(json: any): ServerOperationResponse {
    return ServerOperationResponseToJSONTyped(json, false);
}

export function ServerOperationResponseToJSONTyped(value?: ServerOperationResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'message': value['message'],
        'timestamp': value['timestamp'],
    };
}

