/* tslint:disable */
/* eslint-disable */
/**
 * Proxy Smart
 * SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia
 *
 * The version of the OpenAPI document: 0.0.1-RELEASE.202510170109.139bb12
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SetTenantRequest
 */
export interface SetTenantRequest {
    /**
     * Tenant identifier
     * @type {string}
     * @memberof SetTenantRequest
     */
    tenant: string;
}

/**
 * Check if a given object implements the SetTenantRequest interface.
 */
export function instanceOfSetTenantRequest(value: object): value is SetTenantRequest {
    if (!('tenant' in value) || value['tenant'] === undefined) return false;
    return true;
}

export function SetTenantRequestFromJSON(json: any): SetTenantRequest {
    return SetTenantRequestFromJSONTyped(json, false);
}

export function SetTenantRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetTenantRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'tenant': json['tenant'],
    };
}

export function SetTenantRequestToJSON(json: any): SetTenantRequest {
    return SetTenantRequestToJSONTyped(json, false);
}

export function SetTenantRequestToJSONTyped(value?: SetTenantRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tenant': value['tenant'],
    };
}

