/* tslint:disable */
/* eslint-disable */
/**
 * Proxy Smart
 * SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia
 *
 * The version of the OpenAPI document: 0.0.1-RELEASE.202510170109.139bb12
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateRoleRequest
 */
export interface UpdateRoleRequest {
    /**
     * Role description
     * @type {string}
     * @memberof UpdateRoleRequest
     */
    description?: string;
    /**
     * FHIR scopes associated with this role
     * @type {Array<string>}
     * @memberof UpdateRoleRequest
     */
    fhirScopes?: Array<string>;
}

/**
 * Check if a given object implements the UpdateRoleRequest interface.
 */
export function instanceOfUpdateRoleRequest(value: object): value is UpdateRoleRequest {
    return true;
}

export function UpdateRoleRequestFromJSON(json: any): UpdateRoleRequest {
    return UpdateRoleRequestFromJSONTyped(json, false);
}

export function UpdateRoleRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateRoleRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'] == null ? undefined : json['description'],
        'fhirScopes': json['fhirScopes'] == null ? undefined : json['fhirScopes'],
    };
}

export function UpdateRoleRequestToJSON(json: any): UpdateRoleRequest {
    return UpdateRoleRequestToJSONTyped(json, false);
}

export function UpdateRoleRequestToJSONTyped(value?: UpdateRoleRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'description': value['description'],
        'fhirScopes': value['fhirScopes'],
    };
}

