/* tslint:disable */
/* eslint-disable */
/**
 * Proxy Smart
 * SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia
 *
 * The version of the OpenAPI document: 0.0.1-RELEASE.202510170109.139bb12
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ErrorResponse,
  ExportResponse,
  GetHealth422Response,
  MonitoringHealthResponse,
  OAuthAnalyticsResponse,
  OAuthEventsResponse,
  WebSocketInfoResponse,
} from '../models/index';
import {
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    ExportResponseFromJSON,
    ExportResponseToJSON,
    GetHealth422ResponseFromJSON,
    GetHealth422ResponseToJSON,
    MonitoringHealthResponseFromJSON,
    MonitoringHealthResponseToJSON,
    OAuthAnalyticsResponseFromJSON,
    OAuthAnalyticsResponseToJSON,
    OAuthEventsResponseFromJSON,
    OAuthEventsResponseToJSON,
    WebSocketInfoResponseFromJSON,
    WebSocketInfoResponseToJSON,
} from '../models/index';

export interface GetMonitoringOauthAnalyticsRequest {
    authorization?: string;
}

export interface GetMonitoringOauthAnalyticsExportRequest {
    authorization: string;
}

export interface GetMonitoringOauthAnalyticsStreamRequest {
    token?: string;
    authorization?: string;
}

export interface GetMonitoringOauthEventsRequest {
    limit?: string;
    type?: string;
    status?: string;
    clientId?: string;
    since?: string;
    authorization?: string;
}

export interface GetMonitoringOauthEventsExportRequest {
    authorization: string;
}

export interface GetMonitoringOauthEventsStreamRequest {
    token?: string;
    authorization?: string;
}

export interface GetMonitoringOauthHealthRequest {
    authorization?: string;
}

/**
 * 
 */
export class OauthMonitoringApi extends runtime.BaseAPI {

    /**
     * Get current OAuth analytics and metrics
     * Get OAuth Analytics
     */
    async getMonitoringOauthAnalyticsRaw(requestParameters: GetMonitoringOauthAnalyticsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OAuthAnalyticsResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/monitoring/oauth/analytics`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OAuthAnalyticsResponseFromJSON(jsonValue));
    }

    /**
     * Get current OAuth analytics and metrics
     * Get OAuth Analytics
     */
    async getMonitoringOauthAnalytics(requestParameters: GetMonitoringOauthAnalyticsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OAuthAnalyticsResponse> {
        const response = await this.getMonitoringOauthAnalyticsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Download current OAuth analytics data as JSON file
     * Export Analytics Data
     */
    async getMonitoringOauthAnalyticsExportRaw(requestParameters: GetMonitoringOauthAnalyticsExportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ExportResponse>> {
        if (requestParameters['authorization'] == null) {
            throw new runtime.RequiredError(
                'authorization',
                'Required parameter "authorization" was null or undefined when calling getMonitoringOauthAnalyticsExport().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/monitoring/oauth/analytics/export`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ExportResponseFromJSON(jsonValue));
    }

    /**
     * Download current OAuth analytics data as JSON file
     * Export Analytics Data
     */
    async getMonitoringOauthAnalyticsExport(requestParameters: GetMonitoringOauthAnalyticsExportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ExportResponse> {
        const response = await this.getMonitoringOauthAnalyticsExportRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Server-sent events stream for real-time OAuth analytics updates. Token can be passed as query parameter or Authorization header.
     * OAuth Analytics Stream
     */
    async getMonitoringOauthAnalyticsStreamRaw(requestParameters: GetMonitoringOauthAnalyticsStreamRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        const queryParameters: any = {};

        if (requestParameters['token'] != null) {
            queryParameters['token'] = requestParameters['token'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/monitoring/oauth/analytics/stream`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Server-sent events stream for real-time OAuth analytics updates. Token can be passed as query parameter or Authorization header.
     * OAuth Analytics Stream
     */
    async getMonitoringOauthAnalyticsStream(requestParameters: GetMonitoringOauthAnalyticsStreamRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.getMonitoringOauthAnalyticsStreamRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieve recent OAuth events with optional filtering
     * Get OAuth Events
     */
    async getMonitoringOauthEventsRaw(requestParameters: GetMonitoringOauthEventsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OAuthEventsResponse>> {
        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['type'] != null) {
            queryParameters['type'] = requestParameters['type'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['clientId'] != null) {
            queryParameters['clientId'] = requestParameters['clientId'];
        }

        if (requestParameters['since'] != null) {
            queryParameters['since'] = requestParameters['since'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/monitoring/oauth/events`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OAuthEventsResponseFromJSON(jsonValue));
    }

    /**
     * Retrieve recent OAuth events with optional filtering
     * Get OAuth Events
     */
    async getMonitoringOauthEvents(requestParameters: GetMonitoringOauthEventsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OAuthEventsResponse> {
        const response = await this.getMonitoringOauthEventsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Download OAuth events log as JSONL file
     * Export Events Data
     */
    async getMonitoringOauthEventsExportRaw(requestParameters: GetMonitoringOauthEventsExportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        if (requestParameters['authorization'] == null) {
            throw new runtime.RequiredError(
                'authorization',
                'Required parameter "authorization" was null or undefined when calling getMonitoringOauthEventsExport().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/monitoring/oauth/events/export`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Download OAuth events log as JSONL file
     * Export Events Data
     */
    async getMonitoringOauthEventsExport(requestParameters: GetMonitoringOauthEventsExportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.getMonitoringOauthEventsExportRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Server-sent events stream for real-time OAuth flow monitoring. Token can be passed as query parameter or Authorization header.
     * OAuth Events Stream
     */
    async getMonitoringOauthEventsStreamRaw(requestParameters: GetMonitoringOauthEventsStreamRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        const queryParameters: any = {};

        if (requestParameters['token'] != null) {
            queryParameters['token'] = requestParameters['token'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/monitoring/oauth/events/stream`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Server-sent events stream for real-time OAuth flow monitoring. Token can be passed as query parameter or Authorization header.
     * OAuth Events Stream
     */
    async getMonitoringOauthEventsStream(requestParameters: GetMonitoringOauthEventsStreamRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.getMonitoringOauthEventsStreamRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get OAuth system health metrics and alerts
     * Get System Health
     */
    async getMonitoringOauthHealthRaw(requestParameters: GetMonitoringOauthHealthRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MonitoringHealthResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/monitoring/oauth/health`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MonitoringHealthResponseFromJSON(jsonValue));
    }

    /**
     * Get OAuth system health metrics and alerts
     * Get System Health
     */
    async getMonitoringOauthHealth(requestParameters: GetMonitoringOauthHealthRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MonitoringHealthResponse> {
        const response = await this.getMonitoringOauthHealthRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get information about WebSocket endpoints and supported subscriptions
     * WebSocket Connection Info
     */
    async getOauthMonitoringWebsocketInfoRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WebSocketInfoResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/oauth/monitoring/websocket/info`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WebSocketInfoResponseFromJSON(jsonValue));
    }

    /**
     * Get information about WebSocket endpoints and supported subscriptions
     * WebSocket Connection Info
     */
    async getOauthMonitoringWebsocketInfo(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WebSocketInfoResponse> {
        const response = await this.getOauthMonitoringWebsocketInfoRaw(initOverrides);
        return await response.value();
    }

}
