name: 'Setup Bun with Caching'
description: 'Sets up Bun environment with caching and installs dependencies'

inputs:
  bun-version:
    description: 'Bun version to use'
    required: false
    default: 'latest'
  working-directory:
    description: 'Working directory for Bun operations'
    required: false
    default: '.'

runs:
  using: 'composite'
  steps:
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: ${{ inputs.bun-version }}

    - name: Cache Bun dependencies
      uses: actions/cache@v4
      id: cache-bun
      with:
        path: |
          ~/.bun/install/cache
          node_modules
        key: ${{ runner.os }}-bun-${{ inputs.bun-version }}-${{ hashFiles('**/bun.lockb', '**/bun.lock') }}
        restore-keys: |
          ${{ runner.os }}-bun-${{ inputs.bun-version }}-
          ${{ runner.os }}-bun-

    - name: Install dependencies
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        echo "::group::Install Bun dependencies"
        if [ -f "bun.lockb" ] || [ -f "bun.lock" ]; then
          bun install --frozen-lockfile
        else
          bun install
        fi
        echo "::endgroup::"
