name: Alpha Release

on:
  push:
    branches: [develop]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: read

jobs:
  alpha-release:
    uses: ./.github/workflows/release-template.yml
    with:
      release_type: 'alpha'
      source_branch: 'develop'
      target_branch: 'develop'
      version_suffix: 'alpha'
      should_bump_version: true
      is_prerelease: true
      commit_limit: 10
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
