name: Alpha Release

on:
  push:
    branches: [develop]
    paths-ignore:
      - 'ui/src/lib/api-client/**'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: read

jobs:
  alpha-release:
    # Only run if the last commit is not a release commit to avoid infinite loops
    if: ${{ !contains(github.event.head_commit.message, '🔄 Update version') && !contains(github.event.head_commit.message, '🤖 Update API clients') && !contains(github.event.head_commit.message, 'Alpha release') && !contains(github.event.head_commit.message, '🚀') }}
    uses: ./.github/workflows/release-orchestrator.yml
    with:
      release_type: 'alpha'
      source_branch: 'develop'
      target_branch: 'develop'
      version_suffix: 'alpha'
      should_bump_version: true
      is_prerelease: true
      commit_limit: 10
    secrets:
      APP_ID: ${{ secrets.APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
