name: Alpha Release

on:
  push:
    # Trigger only on alpha tag creation to avoid looping on branch commits
    tags:
      - 'v*-alpha*'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: read

jobs:
  alpha-release:
    uses: ./.github/workflows/release-orchestrator.yml
    with:
      release_type: 'alpha'
      source_branch: 'develop'
      target_branch: 'develop'
      version_suffix: 'alpha'
      should_bump_version: true
      is_prerelease: true
      commit_limit: 10
    secrets:
      APP_ID: ${{ secrets.APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
