name: Beta Release

on:
  push:
    branches: [test]
    paths-ignore:
      - 'ui/src/lib/api-client/**'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: read

concurrency:
  group: releases
  cancel-in-progress: false

jobs:
  # Beta releases run comprehensive testing (unit + integration + E2E)
  beta-testing:
    name: Beta Testing
    if: ${{ !contains(github.event.head_commit.message, '🔄 Update version') && !contains(github.event.head_commit.message, '🤖 Update API clients') && !contains(github.event.head_commit.message, 'Beta release') && !contains(github.event.head_commit.message, '🚀') && !contains(github.event.head_commit.message, 'smart-on-fhir-proxy-releaser') }}
    uses: ./.github/workflows/testing-strategy.yml
    with:
      test_stage: 'beta'
      test_scope: 'all'

  beta-release:
    name: Beta Release
    # Only run if the last commit is not a release commit to avoid infinite loops
    if: ${{ !contains(github.event.head_commit.message, '🔄 Update version') && !contains(github.event.head_commit.message, '🤖 Update API clients') && !contains(github.event.head_commit.message, 'Beta release') && !contains(github.event.head_commit.message, '🚀') && !contains(github.event.head_commit.message, 'smart-on-fhir-proxy-releaser') }}
    needs: [beta-testing]
    uses: ./.github/workflows/release-orchestrator.yml
    with:
      release_type: 'beta'
      source_branch: 'test'
      target_branch: 'test'
      should_bump_version: false
      is_prerelease: true
      commit_limit: 10
    secrets:
      APP_ID: ${{ secrets.APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
