name: Beta Release

on:
  push:
    branches: [test]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: read

jobs:
  beta-release:
    uses: ./.github/workflows/release-template.yml
    with:
      release_type: 'beta'
      source_branch: 'test'
      target_branch: 'test'
      version_suffix: 'beta'
      should_bump_version: false
      is_prerelease: true
      commit_limit: 10
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
