name: Build and Test

on:
  workflow_call:
    inputs:
      run_tests:
        description: "Whether to run tests"
        required: false
        type: boolean
        default: true
      fail_on_test_failure:
        description: "Whether to fail the workflow if tests fail"
        required: false
        type: boolean
        default: false

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Build backend
        run: |
          echo "Building backend..."
          cd backend
          bun install
          bun run build
          cd ..

      - name: Build UI
        run: |
          echo "Building UI..."
          cd ui
          bun install
          bun run build
          cd ..

      - name: Test UI
        continue-on-error: ${{ !inputs.fail_on_test_failure }}
        if: ${{ inputs.run_tests }}
        run: |
          echo "Running UI tests..."
          cd ui
          bun run test
          cd ..

      - name: Test backend
        continue-on-error: ${{ !inputs.fail_on_test_failure }}
        if: ${{ inputs.run_tests }}
        run: |
          echo "Running backend tests..."
          cd backend
          bun run test
          cd ..
