name: Build & Test Backend

on:
  workflow_call:
    inputs:
      run_tests:
        description: "Whether to run tests"
        required: false
        type: boolean
        default: true
      fail_on_test_failure:
        description: "Whether to fail the workflow if tests fail"
        required: false
        type: boolean
        default: false
    outputs:
      backend_success:
        description: "Whether backend build was successful"
        value: ${{ jobs.backend.outputs.build_success }}
      backend_tests_success:
        description: "Whether backend tests were successful"
        value: ${{ jobs.backend.outputs.tests_success }}
    secrets:
      APP_ID:
        required: false
      APP_PRIVATE_KEY:
        required: false
      OPENAI_API_KEY:
        required: false

jobs:
  backend:
    name: Backend Build & Test
    runs-on: ubuntu-latest
    outputs:
      build_success: ${{ steps.backend-build.outcome == 'success' || steps.backend-fix-retry.outcome == 'success' }}
      tests_success: ${{ steps.test-backend.outcome == 'success' || steps.backend-test-fix-retry.outcome == 'success' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun with version scripts
        uses: ./.github/actions/setup-bun-version
        with:
          checkout: 'false'  # Skip checkout since we already did it

      # === BACKEND BUILD PHASE ===
      - name: Build Backend
        id: backend-build
        continue-on-error: true
        run: |
          echo "=== Building Backend ==="
          cd backend
          bun install
          bun run build 2>&1 | tee ../backend-build.log

      - name: Debug Build Failure and Secrets
        if: steps.backend-build.outcome == 'failure'
        run: |
          echo "🐛 Backend build failed, checking AI fix prerequisites..."
          echo "Build outcome: ${{ steps.backend-build.outcome }}"
          echo "Build logs:"
          cat backend-build.log || echo "No build log found"
          echo "APP_ID available: ${{ secrets.APP_ID != '' }}"
          echo "APP_PRIVATE_KEY available: ${{ secrets.APP_PRIVATE_KEY != '' }}"
          echo "OPENAI_API_KEY available: ${{ secrets.OPENAI_API_KEY != '' }}"
          echo "Repository: ${{ github.repository }}"
          echo "Event name: ${{ github.event_name }}"
          echo "Actor: ${{ github.actor }}"

      - name: Authenticate as GitHub App (Backend Build)
        if: steps.backend-build.outcome == 'failure'
        id: backend-app-auth
        continue-on-error: true
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: ${{ github.event.repository.name }}

      - name: Check GitHub App Authentication
        if: steps.backend-build.outcome == 'failure'
        run: |
          if [ "${{ steps.backend-app-auth.outputs.token }}" != "" ]; then
            echo "✅ GitHub App authentication successful"
          else
            echo "❌ GitHub App authentication failed - AI fixes will be skipped"
            echo "This could be due to:"
            echo "  - Missing APP_ID or APP_PRIVATE_KEY secrets"
            echo "  - Insufficient app permissions"
            echo "  - Running on a fork without access to secrets"
            echo "  - GitHub App not installed on this repository"
          fi

      - name: Setup Python for Backend AI fixes
        if: steps.backend-build.outcome == 'failure' && steps.backend-app-auth.outputs.token
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python dependencies for Backend AI fixes
        if: steps.backend-build.outcome == 'failure' && steps.backend-app-auth.outputs.token
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements.txt

      - name: Propose Backend Fixes with Junior AI
        if: steps.backend-build.outcome == 'failure' && steps.backend-app-auth.outputs.token
        id: backend-propose
        continue-on-error: true
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          echo "🤖 Junior AI proposing initial backend fixes..."
          if python scripts/propose-backend-fixes.py backend-build.log > scripts/proposed-backend-fixes.json; then
            echo "✅ Fixes proposed successfully"
            echo "Proposed fixes:"
            cat scripts/proposed-backend-fixes.json
          else
            echo "❌ Failed to propose fixes"
            exit 1
          fi

      - name: Review Proposed Backend Fixes with Senior AI
        if: steps.backend-build.outcome == 'failure' && steps.backend-app-auth.outputs.token
        id: backend-review
        continue-on-error: true
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          echo "🎓 Senior AI reviewing proposed backend fixes..."
          if python scripts/review-backend-fixes.py scripts/proposed-backend-fixes.json backend-build.log > scripts/reviewed-backend-fixes.json; then
            echo "✅ Fixes reviewed successfully"
            echo "Reviewed fixes:"
            cat scripts/reviewed-backend-fixes.json
          else
            echo "❌ Failed to review fixes"
            exit 1
          fi

      - name: Apply Reviewed Backend Fixes and retry build
        if: steps.backend-build.outcome == 'failure' && steps.backend-app-auth.outputs.token
        id: backend-fix-retry
        continue-on-error: true
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ steps.backend-app-auth.outputs.token }}
        run: |
          echo "🔧 Applying reviewed backend fixes..."
          # Ensure log files are not tracked by git
          git reset HEAD *.log 2>/dev/null || true
          git rm --cached *.log 2>/dev/null || true
          python scripts/apply-backend-fixes.py scripts/reviewed-backend-fixes.json

      - name: Fail if backend build failed and AI couldn't fix it
        if: steps.backend-build.outcome == 'failure' && steps.backend-fix-retry.outcome != 'success'
        run: |
          echo "❌ Backend build failed and AI fixes did not resolve the issues"
          echo "Build outcome: ${{ steps.backend-build.outcome }}"
          echo "Fix retry outcome: ${{ steps.backend-fix-retry.outcome }}"
          exit 1

      # === BACKEND TEST PHASE ===
      - name: Test Backend
        if: ${{ inputs.run_tests }}
        continue-on-error: true
        id: test-backend
        run: |
          echo "Running backend tests..."
          cd backend
          bun test 2>&1 | tee ../backend-test.log

      - name: Authenticate as GitHub App (Backend Tests)
        if: ${{ inputs.run_tests }} && steps.test-backend.outcome == 'failure'
        id: backend-test-app-auth
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: ${{ github.event.repository.name }}

      - name: Debug Test Failure
        if: ${{ inputs.run_tests }} && steps.test-backend.outcome == 'failure'
        run: |
          echo "🐛 Backend tests failed, checking details..."
          echo "Test outcome: ${{ steps.test-backend.outcome }}"
          echo "Test logs:"
          cat backend-test.log || echo "No test log found"

      - name: Setup Python for Backend Test AI fixes
        if: ${{ inputs.run_tests }} && steps.test-backend.outcome == 'failure' && steps.backend-test-app-auth.outputs.token
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python dependencies for Backend Test AI fixes
        if: ${{ inputs.run_tests }} && steps.test-backend.outcome == 'failure' && steps.backend-test-app-auth.outputs.token
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements.txt

      - name: Propose Backend Test Fixes with Junior AI
        if: ${{ inputs.run_tests }} && steps.test-backend.outcome == 'failure' && steps.backend-test-app-auth.outputs.token
        id: backend-test-propose
        continue-on-error: true
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          echo "🤖 Junior AI proposing initial backend test fixes..."
          if python scripts/propose-backend-fixes.py backend-test.log > scripts/proposed-backend-test-fixes.json; then
            echo "✅ Test fixes proposed successfully"
            echo "Proposed test fixes:"
            cat scripts/proposed-backend-test-fixes.json
          else
            echo "❌ Failed to propose test fixes"
            exit 1
          fi

      - name: Review Proposed Backend Test Fixes with Senior AI
        if: ${{ inputs.run_tests }} && steps.test-backend.outcome == 'failure' && steps.backend-test-app-auth.outputs.token
        id: backend-test-review
        continue-on-error: true
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          echo "🎓 Senior AI reviewing proposed backend test fixes..."
          if python scripts/review-backend-fixes.py scripts/proposed-backend-test-fixes.json backend-test.log > scripts/reviewed-backend-test-fixes.json; then
            echo "✅ Test fixes reviewed successfully"
            echo "Reviewed test fixes:"
            cat scripts/reviewed-backend-test-fixes.json
          else
            echo "❌ Failed to review test fixes"
            exit 1
          fi

      - name: Apply Reviewed Backend Test Fixes and retry tests
        if: ${{ inputs.run_tests }} && steps.test-backend.outcome == 'failure' && steps.backend-test-app-auth.outputs.token
        id: backend-test-fix-retry
        continue-on-error: true
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ steps.backend-test-app-auth.outputs.token }}
        run: |
          echo "🔧 Applying reviewed backend test fixes..."
          # Ensure log files are not tracked by git
          git reset HEAD *.log 2>/dev/null || true
          git rm --cached *.log 2>/dev/null || true
          python scripts/apply-backend-fixes.py scripts/reviewed-backend-test-fixes.json

      - name: Fail if backend tests failed and AI couldn't fix it
        if: ${{ inputs.run_tests }} && steps.test-backend.outcome == 'failure' && steps.backend-test-fix-retry.outcome != 'success'
        run: |
          echo "Test outcome: ${{ steps.test-backend.outcome }}"
          echo "Fix retry outcome: ${{ steps.backend-test-fix-retry.outcome }}"
          if [ "${{ inputs.fail_on_test_failure }}" == "true" ]; then
            echo "❌ Backend tests failed and AI fixes did not resolve the issues. Failing workflow as requested."
            exit 1
          else
            echo "⚠️ Backend tests failed and AI fixes did not resolve the issues, but continuing workflow as requested."
          fi

      # === API GENERATION (only after successful backend build/test) ===
      - name: Upload backend build artifacts
        if: ${{ !startsWith(github.ref, 'refs/heads/dev/') }}
        uses: actions/upload-artifact@v4
        with:
          name: backend-artifacts
          path: |
            backend/dist/
          retention-days: 1
