name: AI Commit Comment

on:
  push:
    branches:
      - "*"

jobs:
  ai-comment:
    name: Review & Comment on HEAD Commit
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, 'Merge') && !startsWith(github.event.head_commit.message, 'Merge pull request') && !startsWith(github.event.head_commit.message, 'Merge branch') }}
    continue-on-error: true

    steps:
      - name: Checkout full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Authenticate as GitHub App
        id: app-auth
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: ${{ github.event.repository.name }}

      - name: Setup Node.js with AI tools
        uses: ./.github/actions/setup-node-ai
        with:
          checkout: 'false'  # Skip checkout since we already did it
          fetch-depth: 0

      - name: Comment on HEAD commit via ChatGPT
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ steps.app-auth.outputs.token || secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          HEAD_SHA: ${{ github.sha }}
          OPENAI_MODEL: ${{ vars.OPENAI_MODEL || 'gpt-4o-mini' }}
        run: |
          echo "Running AI commit comment script..."
          node scripts/ai-commit-comment.mjs
