name: Deployment Strategy

on:
  workflow_call:
    inputs:
      deployment_stage:
        description: "Deployment stage: alpha, beta, or production"
        required: true
        type: string
      app_version:
        description: "Version of the application to deploy"
        required: true
        type: string
      source_branch:
        description: "Source branch for deployment"
        required: true
        type: string
    outputs:
      fhir_server_url:
        description: "FHIR server URL after deployment"
        value: ${{ jobs.output-deployment-urls.outputs.fhir_server_url }}
      keycloak_url:
        description: "Keycloak URL after deployment"
        value: ${{ jobs.output-deployment-urls.outputs.keycloak_url }}
      deployment_status:
        description: "Status of the deployment"
        value: ${{ jobs.output-deployment-urls.outputs.deployment_status }}
      deployment_target:
        description: "Target platform where app was deployed"
        value: ${{ jobs.output-deployment-urls.outputs.deployment_target }}
    secrets:
      FLY_API_TOKEN:
        required: false
      VPS_SSH_KEY:
        required: false
      VPS_HOST:
        required: false
      VPS_USER:
        required: false

jobs:
  deploy-alpha:
    name: Deploy Alpha (Local)
    runs-on: ubuntu-latest
    if: inputs.deployment_stage == 'alpha'
    outputs:
      fhir_server_url: ${{ steps.deploy.outputs.fhir_server_url }}
      keycloak_url: ${{ steps.deploy.outputs.keycloak_url }}
      deployment_status: ${{ steps.deploy.outputs.deployment_status }}
      deployment_target: ${{ steps.deploy.outputs.deployment_target }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.source_branch }}
      
      - name: Setup Bun
        uses: ./.github/actions/setup-bun-version
      
      - name: Install dependencies
        run: bun install --frozen-lockfile
      
      - name: Deploy Alpha (Local with Docker)
        id: deploy
        run: |
          echo "🚀 Deploying Alpha version ${{ inputs.app_version }} locally using Docker..."
          
          # Start services using Docker (similar to testing but for deployment)
          echo "🐳 Starting PostgreSQL..."
          docker run -d \
            --name alpha-postgres \
            -e POSTGRES_DB=keycloak \
            -e POSTGRES_USER=postgres \
            -e POSTGRES_PASSWORD=postgres \
            -p 5432:5432 \
            postgres:16-alpine
          
          # Wait for PostgreSQL
          echo "⏳ Waiting for PostgreSQL..."
          timeout 60s bash -c 'until docker exec alpha-postgres pg_isready -U postgres; do sleep 2; done'
          
          echo "🔐 Starting Keycloak..."
          docker run -d \
            --name alpha-keycloak \
            --link alpha-postgres:postgres \
            -e KC_BOOTSTRAP_ADMIN_USERNAME=admin \
            -e KC_BOOTSTRAP_ADMIN_PASSWORD=admin \
            -e KC_HTTP_ENABLED=true \
            -e KC_HOSTNAME_STRICT=false \
            -e KC_DB=postgres \
            -e KC_DB_URL=jdbc:postgresql://postgres:5432/keycloak \
            -e KC_DB_USERNAME=postgres \
            -e KC_DB_PASSWORD=postgres \
            -p 8080:8080 \
            quay.io/keycloak/keycloak:26.2 start-dev
          
          # Wait for Keycloak
          echo "⏳ Waiting for Keycloak..."
          timeout 180s bash -c 'until curl -f http://localhost:8080/health/ready; do sleep 5; done'
          
          # Build and start the backend
          echo "🏗️ Building and starting FHIR backend..."
          cd backend
          bun install
          bun run build
          
          # Set environment variables for backend
          export DATABASE_URL="postgresql://postgres:postgres@localhost:5432/keycloak"
          export KEYCLOAK_BASE_URL="http://localhost:8080"
          export KEYCLOAK_REALM="proxy-smart"
          export PORT=3001
          
          # Start the FHIR proxy server in background
          nohup bun run start &
          echo $! > ../backend.pid
          cd ..
          
          # Wait for backend to be ready
          echo "⏳ Waiting for FHIR backend..."
          timeout 120s bash -c 'until curl -f http://localhost:3001/health; do sleep 5; done'
          
          # Set outputs
          echo "fhir_server_url=http://localhost:3001" >> $GITHUB_OUTPUT
          echo "keycloak_url=http://localhost:8080" >> $GITHUB_OUTPUT
          echo "deployment_status=success" >> $GITHUB_OUTPUT
          echo "deployment_target=local" >> $GITHUB_OUTPUT
          
          echo "✅ Alpha deployment completed successfully"
          echo "📍 FHIR Server: http://localhost:3001"
          echo "📍 Keycloak: http://localhost:8080"
          echo "🔍 Backend PID stored in backend.pid for testing phase"

  deploy-beta:
    name: Deploy Beta (Fly.io)
    runs-on: ubuntu-latest
    if: inputs.deployment_stage == 'beta'
    outputs:
      fhir_server_url: ${{ steps.deploy.outputs.fhir_server_url }}
      keycloak_url: ${{ steps.deploy.outputs.keycloak_url }}
      deployment_status: ${{ steps.deploy.outputs.deployment_status }}
      deployment_target: ${{ steps.deploy.outputs.deployment_target }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.source_branch }}
      
      - name: Setup Bun
        uses: ./.github/actions/setup-bun-version
      
      - name: Setup Fly.io CLI
        uses: superfly/flyctl-actions/setup-flyctl@master
      
      - name: Deploy Beta (Fly.io)
        id: deploy
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          echo "🚀 Deploying Beta version ${{ inputs.app_version }} to Fly.io..."
          
          # Create or update fly.beta.toml configuration
          cat > fly.beta.toml << EOF
          app = "proxy-smart-beta"
          primary_region = "ams"
          
          [build]
            dockerfile = "Dockerfile"
          
          [env]
            NODE_ENV = "beta"
            VERSION = "${{ inputs.app_version }}"
          
          [[services]]
            internal_port = 3001
            protocol = "tcp"
          
            [[services.ports]]
              port = 80
              handlers = ["http"]
          
            [[services.ports]]
              port = 443
              handlers = ["http", "tls"]
          
          [[ services.http_checks ]]
            interval = "10s"
            timeout = "2s"
            grace_period = "5s"
            method = "GET"
            path = "/health"
          EOF
          
          # Deploy to Fly.io
          flyctl deploy --config fly.beta.toml --wait-timeout 300
          
          # Get the deployed URL
          FLY_APP_URL="https://proxy-smart-beta.fly.dev"
          
          # Wait for deployment to be ready
          echo "⏳ Waiting for Fly.io deployment to be ready..."
          timeout 300s bash -c "until curl -f $FLY_APP_URL/health; do sleep 10; done"
          
          # Set outputs (assuming Keycloak is also deployed or accessible)
          echo "fhir_server_url=$FLY_APP_URL" >> $GITHUB_OUTPUT
          echo "keycloak_url=https://auth-proxy-smart-beta.fly.dev" >> $GITHUB_OUTPUT
          echo "deployment_status=success" >> $GITHUB_OUTPUT
          echo "deployment_target=fly.io" >> $GITHUB_OUTPUT
          
          echo "✅ Beta deployment completed successfully"
          echo "📍 FHIR Server: $FLY_APP_URL"
          echo "📍 Keycloak: https://auth-proxy-smart-beta.fly.dev"

  deploy-production:
    name: Deploy Production (VPS)
    runs-on: ubuntu-latest
    if: inputs.deployment_stage == 'production'
    outputs:
      fhir_server_url: ${{ steps.deploy.outputs.fhir_server_url }}
      keycloak_url: ${{ steps.deploy.outputs.keycloak_url }}
      deployment_status: ${{ steps.deploy.outputs.deployment_status }}
      deployment_target: ${{ steps.deploy.outputs.deployment_target }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.source_branch }}
      
      - name: Setup Bun
        uses: ./.github/actions/setup-bun-version
      
      - name: Deploy Production (VPS)
        id: deploy
        run: |
          echo "🚀 Deploying Production version ${{ inputs.app_version }} to VPS..."
          
          # Setup SSH key
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts
          
          # Create deployment script
          cat > deploy-to-vps.sh << 'EOF'
          #!/bin/bash
          set -e
          
          echo "📦 Updating application on VPS..."
          
          # Navigate to application directory
          cd /opt/proxy-smart
          
          # Pull latest changes
          git fetch origin
          git checkout ${{ inputs.source_branch }}
          git pull origin ${{ inputs.source_branch }}
          
          # Install dependencies and build
          bun install --frozen-lockfile
          cd backend && bun install && bun run build && cd ..
          cd ui && bun install && bun run build && cd ..
          
          # Restart services using Docker Compose
          docker-compose down
          docker-compose up -d --build
          
          # Wait for services to be ready
          timeout 120s bash -c 'until curl -f http://localhost:3001/health; do sleep 5; done'
          
          echo "✅ VPS deployment completed"
          EOF
          
          # Make script executable and copy to VPS
          chmod +x deploy-to-vps.sh
          scp deploy-to-vps.sh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/tmp/
          
          # Execute deployment on VPS
          ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "bash /tmp/deploy-to-vps.sh"
          
          # Set outputs
          PRODUCTION_URL="https://your-production-domain.com"
          KEYCLOAK_URL="https://auth.your-production-domain.com"
          
          echo "fhir_server_url=$PRODUCTION_URL" >> $GITHUB_OUTPUT
          echo "keycloak_url=$KEYCLOAK_URL" >> $GITHUB_OUTPUT
          echo "deployment_status=success" >> $GITHUB_OUTPUT
          echo "deployment_target=vps" >> $GITHUB_OUTPUT
          
          echo "✅ Production deployment completed successfully"
          echo "📍 FHIR Server: $PRODUCTION_URL"
          echo "📍 Keycloak: $KEYCLOAK_URL"

  output-deployment-urls:
    name: Output Deployment URLs
    runs-on: ubuntu-latest
    needs: [deploy-alpha, deploy-beta, deploy-production]
    if: always()
    outputs:
      fhir_server_url: ${{ steps.set-outputs.outputs.fhir_server_url }}
      keycloak_url: ${{ steps.set-outputs.outputs.keycloak_url }}
      deployment_status: ${{ steps.set-outputs.outputs.deployment_status }}
      deployment_target: ${{ steps.set-outputs.outputs.deployment_target }}
    
    steps:
      - name: Set deployment outputs
        id: set-outputs
        run: |
          if [ "${{ inputs.deployment_stage }}" = "alpha" ]; then
            echo "fhir_server_url=${{ needs.deploy-alpha.outputs.fhir_server_url }}" >> $GITHUB_OUTPUT
            echo "keycloak_url=${{ needs.deploy-alpha.outputs.keycloak_url }}" >> $GITHUB_OUTPUT
            echo "deployment_status=${{ needs.deploy-alpha.outputs.deployment_status }}" >> $GITHUB_OUTPUT
            echo "deployment_target=${{ needs.deploy-alpha.outputs.deployment_target }}" >> $GITHUB_OUTPUT
          elif [ "${{ inputs.deployment_stage }}" = "beta" ]; then
            echo "fhir_server_url=${{ needs.deploy-beta.outputs.fhir_server_url }}" >> $GITHUB_OUTPUT
            echo "keycloak_url=${{ needs.deploy-beta.outputs.keycloak_url }}" >> $GITHUB_OUTPUT
            echo "deployment_status=${{ needs.deploy-beta.outputs.deployment_status }}" >> $GITHUB_OUTPUT
            echo "deployment_target=${{ needs.deploy-beta.outputs.deployment_target }}" >> $GITHUB_OUTPUT
          elif [ "${{ inputs.deployment_stage }}" = "production" ]; then
            echo "fhir_server_url=${{ needs.deploy-production.outputs.fhir_server_url }}" >> $GITHUB_OUTPUT
            echo "keycloak_url=${{ needs.deploy-production.outputs.keycloak_url }}" >> $GITHUB_OUTPUT
            echo "deployment_status=${{ needs.deploy-production.outputs.deployment_status }}" >> $GITHUB_OUTPUT
            echo "deployment_target=${{ needs.deploy-production.outputs.deployment_target }}" >> $GITHUB_OUTPUT
          fi
      
      - name: Deployment Summary
        run: |
          echo "## Deployment Summary for ${{ inputs.deployment_stage }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Version**: ${{ inputs.app_version }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Target**: ${{ steps.set-outputs.outputs.deployment_target }}" >> $GITHUB_STEP_SUMMARY
          echo "- **FHIR Server**: ${{ steps.set-outputs.outputs.fhir_server_url }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Keycloak**: ${{ steps.set-outputs.outputs.keycloak_url }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Status**: ✅ Success" >> $GITHUB_STEP_SUMMARY
