name: Production Release

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: read

jobs:
  production-release:
    uses: ./.github/workflows/release-template.yml
    with:
      release_type: 'production'
      source_branch: 'main'
      target_branch: 'main'
      version_suffix: 'RELEASE'
      should_bump_version: false
      is_prerelease: false
      commit_limit: 20
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
