name: Production Release

on:
  push:
    # Trigger only on production tag creation to avoid looping on branch commits
    tags:
      - 'v*-RELEASE*'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: read

jobs:
  production-release:
    uses: ./.github/workflows/release-orchestrator.yml
    with:
      release_type: 'production'
      source_branch: 'main'
      target_branch: 'main'
      version_suffix: 'RELEASE'
      should_bump_version: false
      is_prerelease: false
      commit_limit: 20
    secrets:
      APP_ID: ${{ secrets.APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
