name: Version Validation

on:
  pull_request:
    branches: [main, develop, test]

permissions:
  contents: read
  pull-requests: read

jobs:
  validate-versions:
    name: Validate Version Consistency
    uses: ./.github/workflows/version-operations.yml
    with:
      operation: 'validate'
